In [5]:
import pandas as pd
lap_times = pd.read_csv('lap_times.csv')
race_841 = lap_times.query('raceId == 841')

In [19]:
df = race_841.query('lap == 11').sort_values(['position'], ascending = True)

In [20]:
df

      raceId  driverId  lap  position      time  milliseconds
10       841        20   11         1  1:32.669         92669
68       841         1   11         2  1:32.737         92737
184      841       808   11         3  1:33.611         93611
300      841        18   11         4  1:34.396         94396
438      841         4   11         5  1:34.857         94857
242      841        13   11         6  1:36.699         96699
126      841        17   11         7  1:54.995        114995
358      841         3   11         8  1:34.097         94097
380      841       155   11         9  1:34.586         94586
553      841        67   11        10  1:34.479         94479
610      841        16   11        11  1:34.061         94061
496      841       814   11        12  1:34.697         94697
667      841         2   11        13  1:34.838         94838
969      841        22   11        14  1:34.947         94947
724      841       815   11        15  1:34.646         94646
782      841         5   11        16  1:35.907         95907
1017     841       153   11        17  1:35.061         95061
810      841        15   11        18  1:36.703         96703
920      841        10   11        19  1:36.606         96606
866      841       816   11        20  1:37.731         97731
1074     841        30   11        21  1:37.483         97483

In [7]:
lap_positions = pd.DataFrame({'lap': [i for i in range(1,59)]}, \
                             columns = ['lap', 'first_driver', 'second_driver', 'third_driver'])

In [21]:
for i in range(1,59): 
    k = i
    lap_positions.iloc[i-1, 0] = i
    lap_positions.iloc[i-1, 1] = race_841.query('lap == @k').sort_values(['position'], ascending = True).iloc[0,1]
    lap_positions.iloc[i-1, 2] = race_841.query('lap == @k').sort_values(['position'], ascending = True).iloc[1,1]
    lap_positions.iloc[i-1, 3] = race_841.query('lap == @k').sort_values(['position'], ascending = True).iloc[2,1]

In [22]:
lap_positions

    lap first_driver second_driver third_driver
0     1           20             1           17
1     2           20             1           17
2     3           20             1           17
3     4           20             1           17
4     5           20             1           17
5     6           20             1           17
6     7           20             1           17
7     8           20             1           17
8     9           20             1           17
9    10           20             1           17
10   11           20             1          808
11   12           20             1          808
12   13           20             1          808
13   14            1           808           20
14   15            1           808           18
15   16            1            20           18
16   17           20             1           17
17   18           20             1           17
18   19           20             1           17
19   20           20             1           17
20   21           20             1           17
21   22           20             1           17
22   23           20             1           17
23   24           20             1           17
24   25           20             1           17
25   26           20             1          808
26   27           20             1          808
27   28           20             1          808
28   29           20             1          808
29   30           20             1          808
30   31           20             1          808
31   32           20             1          808
32   33           20             1          808
33   34           20             1          808
34   35           20             1          808
35   36           20             1           17
36   37           20             1           17
37   38           20             1           17
38   39           20             1           17
39   40           20             1           17
40   41           20             1            4
41   42           20             1          808
42   43           20             1          808
43   44           20             1          808
44   45           20             1          808
45   46           20             1          808
46   47           20             1          808
47   48           20             1          808
48   49           20             1          808
49   50           20             1          808
50   51           20             1          808
51   52           20             1          808
52   53           20             1          808
53   54           20             1          808
54   55           20             1          808
55   56           20             1          808
56   57           20             1          808
57   58           20             1          808